apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    name: ''
    namespace: cluster-config
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx/'
    targetRevision: 4.3.0
    chart: ingress-nginx
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
